volumes:
  ego_postgresql_data:

services:
  ego-db:
    image: '${POSTGRES_IMAGE}'
    environment:
      PGPORT: 5432
      POSTGRES_DB: ego
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - 'ego_postgresql_data:/egodb'
    ports:
      - 18888:5432
